<?php

/**
 * @file
 * DKAN Examples file.
 */

/**
 * Implements hook_migrate_api().
 */
function dkan_migrate_base_example_migrate_api() {
  $api = array(
    // Migrate API, not CKAN's of course.
    'api' => 2,
    'groups' => array(
      'dkan_migrate_base_example' => array(
        'title' => t('DKAN Examples'),
      ),
    ),
    'migrations' => array(
      'ckan_dataset_migrate_base_example' => array(
        'class_name' => 'MigrateCkanDatasetExample',
        'group_name' => 'dkan_migrate_base_example',
        'title' => t('DKAN Demo  Datasets'),
      ),
      'ckan_dataset_migrate_base_example_resources' => array(
        'class_name' => 'MigrateCkanResourcesExample',
        'group_name' => 'dkan_migrate_base_example',
        'title' => t('DKAN Demo  Resources'),
      ),
    ),
  );
  return $api;
}

class MigrateCkanDatasetExample extends MigrateCkanBase {
  /**
   * Add endpoint.
   */
  public function __construct($arguments) {
    parent::__construct($arguments);
    $fields = $this->getCkanDatasetFields();

    $arguments['endpoint'] = 'http://demo.getdkan.com/api/3/action/';
    //$arguments['endpoint'] = 'http://hub.healthdata.gov/api/3/action/';
    $list_url = isset($arguments['list_url']) ? $arguments['list_url'] : 'package_list';
    $list_url = $arguments['endpoint'] . $list_url;
    $item_url = isset($arguments['item_url']) ? $arguments['item_url'] : 'package_show?id=:id';
    $item_url = $arguments['endpoint'] . $item_url;

    $this->highwaterField = array(
      'name' => 'revision_timestamp',
    );

    $this->source = new MigrateSourceList(new CKANlistJSON($list_url),
          new CKANItemJSON($item_url, $fields), $fields);
    $this->map = new MigrateSQLMap(
            $this->machineName,
            array(
              'uuid' => array(
                'type' => 'varchar',
                'length' => 255,
                'not null' => TRUE,
                'description' => 'id',
              ),
            ),
            MigrateDestinationNode::getKeySchema()
        );

    $this->destination = new MigrateDestinationNode('dataset', array('text_format' => 'html'));

    $this->addDefaultDatasetMappings();
  }

  /**
   * Implements prepareRow.
   */
  public function prepareRow($row) {
    $this->createAndMapResources($row);
    $this->createAndMapGroups($row);
    $this->datasetPrepareRow($row);
  }
}
class MigrateCkanResourcesExample extends MigrateCkanResourceBase {
  /**
   * Add endpoint.
   */
  public function __construct($arguments) {
    $arguments['endpoint'] = 'http://hub.healthdata.gov/api/3/action/';
    parent::__construct($arguments);
  }

  /**
   * Implements prepareRow().
   */
  public function prepareRow($row) {
    parent::prepareRow($row);
  }
}

/**
 * Deregisters DKAN example migrations.
 */
function dkan_migrate_base_example_migrations_disable() {
  Migration::deregisterMigration('ckan_dataset_migrate_base_example');
}
